# Site settings
# baseurl = "https://cp-videos.netlify.app/"
baseurl = "https://elastic-mclean-778d36.netlify.app/"
languageCode = "fr-fr"
title = "CP Vidéos : catalogue de vidéos de Poker live"
theme = ["hugrid-2020"]

# Configuration des folders
contentdir  = "content"
datadir     = "data"
layoutdir   = "layouts"
publishdir  = "public"

disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[build]
  writeStats = false

[module]
   [[module.imports]]
      path = "github.com/divinerites/plausible-hugo"
   #[[module.imports]]
   #   path = "github.com/gohugoio/hugo-mod-bootstrap-scss-v4"

# Pour générer le _redirects pour Netlify avec /layout/index.redir
[outputs]
home = [ "HTML", "HEADERS" ]

[mediaTypes]
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

[outputFormats]
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

[params]
   # Meta
   title = "CP Vidéos : catalogue de vidéos de Poker live"
   subtitle = "Catalogue de vidéos de poker live, préservées et présentées via Club Poker"
   author = "Divinerites"
   description = "Catalogue de vidéos de poker live, préservées et présentées via Club Poker"
   keywords = "Hugo, Poker, Vidéos, ClubPoker, EPT, WSOP, WPT"

   # Body background color
   bodybgcolor = "#f9f9f9"

   # Preview container button text
   buttontext = "Charger la vidéo"

   # Footer text
   footertext = "Videos proposées par Holalahola - Web site par Divinerites"

   # Dates
   dateFormat = "2 Jan 2006"
   dateFormatFull = "02/01/2006"
   dateFormatTime = "2 Jan 2006 15:04"

   # add extra-css
   custom_css = ['css/extra1.css']

   [params.plausible]
      enable = true
      domain = "videos-cp"
      # debug = true
