[build]
publish = "public"
command = "hugo --minify"
functions = "functions"

[context.production.environment]
HUGO_VERSION = "0.87.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
TZ = "Europe/Zurich"

[context.deploy-preview]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.87.0"
HUGO_ENABLEGITINFO = "true"
TZ = "Europe/Zurich"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.87.0"
HUGO_ENABLEGITINFO = "true"
TZ = "Europe/Zurich"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, s-maxage=604800"
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=604800, s-maxage=604800"
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=604800, s-maxage=604800"
[[headers]]
  for = "/*.gif"
  [headers.values]
    Cache-Control = "public, max-age=604800, s-maxage=604800"
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800, s-maxage=604800"
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800, s-maxage=604800"
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, s-maxage=604800"
